In [13]:
import pandas as pd

In [14]:
kospi_3 = pd.read_csv("./율3분기.csv")

In [15]:
kospi3 = pd.read_csv("./kospi3.csv")

In [16]:
kospi3

,Unnamed: 0,회사명,거래소코드,회계년도,당기순이익,주당순손익,부채,매출액,자본,영업손익,부채비율,매출액정상영업이익률
0,0,(주)BNK금융지주,138930,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,(주)BNK금융지주,138930,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,(주)BNK금융지주,138930,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,(주)BNK금융지주,138930,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,(주)BNK금융지주,138930,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2641,2641,효성티앤씨(주),298020,2018,23132399.0,0.0,2.817659e+09,1.972074e+09,4.828314e+08,8.367966e+07,583.570009,4.243231
2642,2642,효성티앤씨(주),298020,2019,79933417.0,0.0,2.820641e+09,4.512551e+09,5.579122e+08,2.392986e+08,505.570765,5.302956
2643,2643,효성티앤씨(주),298020,2020,57455225.0,0.0,2.294985e+09,3.695389e+09,6.234216e+08,1.364577e+08,368.127280,3.692649
2644,2644,효성티앤씨(주),298020,2021,790332475.0,0.0,2.592636e+09,6.148409e+09,1.562677e+09,1.067770e+09,165.909917,17.366611
2645,2645,효성티앤씨(주),298020,2022,26140877.0,0.0,3.464575e+09,7.071677e+09,1.654148e+09,1.668028e+08,209.447660,2.358745

In [17]:
kospi3 = kospi3[['회사명', '거래소코드', '회계년도', '주당순손익', '부채비율', '매출액정상영업이익률']]

In [18]:
kospi3

             회사명   거래소코드  회계년도  주당순손익        부채비율  매출액정상영업이익률
0     (주)BNK금융지주  138930  2011    NaN         NaN         NaN
1     (주)BNK금융지주  138930  2012    NaN         NaN         NaN
2     (주)BNK금융지주  138930  2013    NaN         NaN         NaN
3     (주)BNK금융지주  138930  2014    NaN         NaN         NaN
4     (주)BNK금융지주  138930  2015    NaN         NaN         NaN
...          ...     ...   ...    ...         ...         ...
2641    효성티앤씨(주)  298020  2018    0.0  583.570009    4.243231
2642    효성티앤씨(주)  298020  2019    0.0  505.570765    5.302956
2643    효성티앤씨(주)  298020  2020    0.0  368.127280    3.692649
2644    효성티앤씨(주)  298020  2021    0.0  165.909917   17.366611
2645    효성티앤씨(주)  298020  2022    0.0  209.447660    2.358745

[2646 rows x 6 columns]

In [19]:
kospi_3 = kospi_3[['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율']]

In [25]:
kospi_3['회계년도'] = kospi_3['회계년도'].astype(str)
kospi3['회계년도'] = kospi3['회계년도'].astype(str)
kospi_3['회사명'] = kospi_3['회사명'].astype(str)
kospi3['회사명'] = kospi3['회사명'].astype(str)
kospi_3['거래소코드'] = kospi_3['거래소코드'].astype(str)
kospi3['거래소코드'] = kospi3['거래소코드'].astype(str)

/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_5712/1041076596.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi3['회계년도'] = kospi3['회계년도'].astype(str)
/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_5712/1041076596.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi3['회사명'] = kospi3['회사명'].astype(str)
/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_5712/1041076596.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi3['거래소코드'] = kospi3['거래소코드'].astype(str)

In [26]:
kospi_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2520 entries, 0 to 2519
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   회사명        2520 non-null   object
 1   거래소코드      2520 non-null   object
 2   회계년도       2520 non-null   object
 3   정상영업이익증가율  2306 non-null   float64
 4   순이익증가율     2306 non-null   float64
 5   매출액증가율     2306 non-null   float64
dtypes: float64(3), object(3)
memory usage: 118.2+ KB

In [27]:
kospi3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2646 entries, 0 to 2645
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   회사명         2646 non-null   object
 1   거래소코드       2646 non-null   object
 2   회계년도        2646 non-null   object
 3   주당순손익       2352 non-null   float64
 4   부채비율        2352 non-null   float64
 5   매출액정상영업이익률  2352 non-null   float64
dtypes: float64(3), object(3)
memory usage: 124.2+ KB

In [28]:
k_3 = pd.DataFrame(columns=kospi_3.columns)  # 빈 데이터프레임 생성
k_3_ = pd.DataFrame(columns=kospi3.columns)  # 빈 데이터프레임 생성

for i in range(len(kospi_3)):
    for j in range(len(kospi3)):
        if (kospi_3.loc[i, '회사명'] == kospi3.loc[j, '회사명'] and
            kospi_3.loc[i, '거래소코드'] == kospi3.loc[j, '거래소코드'] and
            kospi_3.loc[i, '회계년도'] == kospi3.loc[j, '회계년도']):
            k_3 = pd.concat([k_3, kospi_3.loc[[i]]], ignore_index=True)
            k_3_ = pd.concat([k_3_, kospi3.loc[[j]]], ignore_index=True)
            break

In [29]:
k_3

             회사명   거래소코드  회계년도   정상영업이익증가율      순이익증가율     매출액증가율
0     (주)BNK금융지주  138930  2011         NaN         NaN        NaN
1     (주)BNK금융지주  138930  2012         NaN         NaN        NaN
2     (주)BNK금융지주  138930  2013         NaN         NaN        NaN
3     (주)BNK금융지주  138930  2014         NaN         NaN        NaN
4     (주)BNK금융지주  138930  2015         NaN         NaN        NaN
...          ...     ...   ...         ...         ...        ...
2515   효성첨단소재(주)  298050  2022  -32.296112  -55.155613  -4.830042
2516    효성티앤씨(주)  298020  2019   -0.195735 -102.126905   2.584437
2517    효성티앤씨(주)  298020  2020 -906.766857 -359.566441  29.412725
2518    효성티앤씨(주)  298020  2021   12.101227    3.703581  11.491809
2519    효성티앤씨(주)  298020  2022 -226.688224 -384.848013 -15.470640

[2520 rows x 6 columns]

In [30]:
kospi3 = pd.concat([k_3[['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율']], k_3_[['주당순손익', '부채비율', '매출액정상영업이익률']]], axis=1)

In [31]:
kospi3

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,매출액증가율,주당순손익,부채비율,매출액정상영업이익률
0,(주)BNK금융지주,138930,2011,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2515,효성첨단소재(주),298050,2022,-32.296112,-55.155613,-4.830042,0.0,291.193755,8.832273
2516,효성티앤씨(주),298020,2019,-0.195735,-102.126905,2.584437,0.0,505.570765,5.302956
2517,효성티앤씨(주),298020,2020,-906.766857,-359.566441,29.412725,0.0,368.127280,3.692649
2518,효성티앤씨(주),298020,2021,12.101227,3.703581,11.491809,0.0,165.909917,17.366611
2519,효성티앤씨(주),298020,2022,-226.688224,-384.848013,-15.470640,0.0,209.447660,2.358745

In [32]:
kospi3.to_csv('3Q.csv', encoding='utf-8-sig')

In [ ]:
kospi_3 = pd.read_csv("./율3분기.csv")