In [292]:
import pandas as pd
import numpy as np

In [293]:
kospi_1 = pd.read_csv("./거시경제변수데이터/코스피200_사업보고서연결.csv", encoding = "euc-kr")
kospi_2 = pd.read_csv("./거시경제변수데이터/코스피200_사업보고서개별.csv", encoding = "euc-kr")
kospi_3 = pd.read_csv("./거시경제변수데이터/코스피200_반기보고서연결.csv", encoding = "euc-kr")
kospi_4 = pd.read_csv("./거시경제변수데이터/코스피200_반기보고서개별.csv", encoding = "euc-kr")

In [294]:
kospi_1.columns = ['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '1주당순이익', '부채비율', '매출액정상영업이익률', '매출액증가율', 'PER(최고)(IFRS)', 'PER(최저)(IFRS)', 'PBR(최고)(IFRS)', 'PBR(최저)(IFRS)', 'PCR(최고)(IFRS)', 'PCR(최저)(IFRS)']
kospi_3.columns = ['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '1주당순이익', '부채비율', '매출액정상영업이익률', '매출액증가율', 'PER(최고)(IFRS)', 'PER(최저)(IFRS)', 'PBR(최고)(IFRS)', 'PBR(최저)(IFRS)', 'PCR(최고)(IFRS)', 'PCR(최저)(IFRS)']

In [295]:
kospi_2.columns = ['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '1주당순이익', '부채비율', '매출액정상영업이익률', '매출액증가율']
kospi_4.columns = ['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '1주당순이익', '부채비율', '매출액정상영업이익률', '매출액증가율']

In [296]:
kospi_c = kospi_1[['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '1주당순이익', '부채비율', '매출액정상영업이익률', '매출액증가율']]
kospi_d = kospi_3[['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '1주당순이익', '부채비율', '매출액정상영업이익률', '매출액증가율']]

In [297]:
kospi = kospi_c.fillna(kospi_2)
kospii = kospi_d.fillna(kospi_4)

In [298]:
kospi_ = kospi_1[['PER(최고)(IFRS)', 'PER(최저)(IFRS)', 'PBR(최고)(IFRS)', 'PBR(최저)(IFRS)', 'PCR(최고)(IFRS)', 'PCR(최저)(IFRS)']]
kospi__ = kospi_3[['PER(최고)(IFRS)', 'PER(최저)(IFRS)', 'PBR(최고)(IFRS)', 'PBR(최저)(IFRS)', 'PCR(최고)(IFRS)', 'PCR(최저)(IFRS)']]

In [299]:
kospi.isna().sum()

회사명             0
거래소코드           0
회계년도            0
정상영업이익증가율     397
순이익증가율        397
1주당순이익        397
부채비율          397
매출액정상영업이익률    397
매출액증가율        397
dtype: int64

In [300]:
kospii.isna().sum()

회사명             0
거래소코드           0
회계년도            0
정상영업이익증가율     349
순이익증가율        349
1주당순이익        349
부채비율          349
매출액정상영업이익률    349
매출액증가율        349
dtype: int64

In [301]:
kospi = pd.concat([kospi, kospi_], axis=1)
kospii = pd.concat([kospii, kospi__], axis=1)

In [302]:
kospi.isna().sum()

회사명                0
거래소코드              0
회계년도               0
정상영업이익증가율        397
순이익증가율           397
1주당순이익           397
부채비율             397
매출액정상영업이익률       397
매출액증가율           397
PER(최고)(IFRS)    397
PER(최저)(IFRS)    397
PBR(최고)(IFRS)    397
PBR(최저)(IFRS)    397
PCR(최고)(IFRS)    397
PCR(최저)(IFRS)    397
dtype: int64

In [303]:
kospii.isna().sum()

회사명                 0
거래소코드               0
회계년도                0
정상영업이익증가율         349
순이익증가율            349
1주당순이익            349
부채비율              349
매출액정상영업이익률        349
매출액증가율            349
PER(최고)(IFRS)     349
PER(최저)(IFRS)     349
PBR(최고)(IFRS)    2639
PBR(최저)(IFRS)    2639
PCR(최고)(IFRS)     349
PCR(최저)(IFRS)     349
dtype: int64

In [304]:
kospii

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,1주당순이익,부채비율,매출액정상영업이익률,매출액증가율,PER(최고)(IFRS),PER(최저)(IFRS),PBR(최고)(IFRS),PBR(최저)(IFRS),PCR(최고)(IFRS),PCR(최저)(IFRS)
0,(주)BNK금융지주,138930,2011/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2634,효성티앤씨(주),298020,2018/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2635,효성티앤씨(주),298020,2019/06,551.38,0.00,14680.0,477.87,5.00,530.33,26.28,12.16,NaN,NaN,9.68,4.48
2636,효성티앤씨(주),298020,2020/06,-52.21,-89.17,1590.0,427.40,2.94,-18.63,23.46,9.73,NaN,NaN,22.53,9.35
2637,효성티앤씨(주),298020,2021/06,801.67,5379.39,87118.0,201.77,16.86,57.09,25.46,2.69,NaN,NaN,27.89,2.94
2638,효성티앤씨(주),298020,2022/06,-56.21,-74.84,21917.0,210.84,5.66,30.43,18.52,6.38,NaN,NaN,0.00,0.00

In [305]:
kospi['회계년도'].unique()

array(['2011/12', '2012/12', '2013/12', '2014/12', '2015/12', '2016/12',
       '2017/12', '2018/12', '2019/12', '2020/12', '2021/12', '2022/12',
       '2007/12', '2008/12', '2009/12', '2010/12', '2007/03', '2008/03',
       '2009/03', '2010/03', '2011/03', '2012/03', '2013/03'],
      dtype=object)

In [306]:
kospii['회계년도'].unique()

array(['2011/06', '2012/06', '2013/06', '2014/06', '2015/06', '2016/06',
       '2017/06', '2018/06', '2019/06', '2020/06', '2021/06', '2022/06',
       '2007/06', '2008/06', '2009/06', '2010/06', '2007/09', '2008/09',
       '2009/09', '2010/09', '2011/09', '2012/09', '2013/09'],
      dtype=object)

In [307]:
kospi = kospi.reset_index(drop=True)

In [308]:
kospi.isna().sum()

회사명                0
거래소코드              0
회계년도               0
정상영업이익증가율        397
순이익증가율           397
1주당순이익           397
부채비율             397
매출액정상영업이익률       397
매출액증가율           397
PER(최고)(IFRS)    397
PER(최저)(IFRS)    397
PBR(최고)(IFRS)    397
PBR(최저)(IFRS)    397
PCR(최고)(IFRS)    397
PCR(최저)(IFRS)    397
dtype: int64

In [309]:
len(kospi["회사명"].unique())

200

In [310]:
kospi["PER"] = (kospi["PER(최고)(IFRS)"] + kospi["PER(최저)(IFRS)"])/2
kospi["PBR"] = (kospi["PBR(최고)(IFRS)"] + kospi["PBR(최저)(IFRS)"])/2
kospi["PCR"] = (kospi["PCR(최고)(IFRS)"] + kospi["PCR(최저)(IFRS)"])/2

In [311]:
kospii["PER"] = (kospii["PER(최고)(IFRS)"] + kospii["PER(최저)(IFRS)"])/2
kospii["PBR"] = (kospii["PBR(최고)(IFRS)"] + kospii["PBR(최저)(IFRS)"])/2
kospii["PCR"] = (kospii["PCR(최고)(IFRS)"] + kospii["PCR(최저)(IFRS)"])/2

In [312]:
kospi.drop(["PER(최고)(IFRS)", "PER(최저)(IFRS)", "PBR(최고)(IFRS)", "PBR(최저)(IFRS)", "PCR(최고)(IFRS)", "PCR(최저)(IFRS)"], axis=1, inplace=True)
kospii.drop(["PER(최고)(IFRS)", "PER(최저)(IFRS)", "PBR(최고)(IFRS)", "PBR(최저)(IFRS)", "PCR(최고)(IFRS)", "PCR(최저)(IFRS)"], axis=1, inplace=True)

In [313]:
kospi

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,1주당순이익,부채비율,매출액정상영업이익률,매출액증가율,PER,PBR,PCR
0,(주)BNK금융지주,138930,2011/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2825,효성티앤씨(주),298020,2018/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2826,효성티앤씨(주),298020,2019/12,158.22,338.18,21569.0,453.10,5.40,78.12,359.480,2.000,5.120
2827,효성티앤씨(주),298020,2020/12,-17.45,46.96,31698.0,294.79,5.16,-13.73,10.240,1.375,3.240
2828,효성티앤씨(주),298020,2021/12,434.08,463.14,178503.0,156.66,16.56,66.54,9.165,4.770,12.370
2829,효성티앤씨(주),298020,2022/12,-91.32,-98.50,2686.0,185.04,1.39,3.34,6.485,2.415,7.755

In [314]:
kospii

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,1주당순이익,부채비율,매출액정상영업이익률,매출액증가율,PER,PBR,PCR
0,(주)BNK금융지주,138930,2011/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2634,효성티앤씨(주),298020,2018/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2635,효성티앤씨(주),298020,2019/06,551.38,0.00,14680.0,477.87,5.00,530.33,19.220,NaN,7.080
2636,효성티앤씨(주),298020,2020/06,-52.21,-89.17,1590.0,427.40,2.94,-18.63,16.595,NaN,15.940
2637,효성티앤씨(주),298020,2021/06,801.67,5379.39,87118.0,201.77,16.86,57.09,14.075,NaN,15.415
2638,효성티앤씨(주),298020,2022/06,-56.21,-74.84,21917.0,210.84,5.66,30.43,12.450,NaN,0.000

In [315]:
kospi['회계년도'].unique()

array(['2011/12', '2012/12', '2013/12', '2014/12', '2015/12', '2016/12',
       '2017/12', '2018/12', '2019/12', '2020/12', '2021/12', '2022/12',
       '2007/12', '2008/12', '2009/12', '2010/12', '2007/03', '2008/03',
       '2009/03', '2010/03', '2011/03', '2012/03', '2013/03'],
      dtype=object)

In [316]:
kospii['회계년도'].unique()

array(['2011/06', '2012/06', '2013/06', '2014/06', '2015/06', '2016/06',
       '2017/06', '2018/06', '2019/06', '2020/06', '2021/06', '2022/06',
       '2007/06', '2008/06', '2009/06', '2010/06', '2007/09', '2008/09',
       '2009/09', '2010/09', '2011/09', '2012/09', '2013/09'],
      dtype=object)

In [317]:
kospi[kospi['회계년도'] == '2022/11']

Empty DataFrame
Columns: [회사명, 거래소코드, 회계년도, 정상영업이익증가율, 순이익증가율, 1주당순이익, 부채비율, 매출액정상영업이익률, 매출액증가율, PER, PBR, PCR]
Index: []

In [318]:
kospi = kospi[kospi['회계년도'].str.contains(r'\d{4}/12')]

In [319]:
kospii = kospii[kospii['회계년도'].str.contains(r'\d{4}/06')]

In [320]:
kospi.reset_index(drop=True)

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,1주당순이익,부채비율,매출액정상영업이익률,매출액증가율,PER,PBR,PCR
0,(주)BNK금융지주,138930,2011/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2731,효성티앤씨(주),298020,2018/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2732,효성티앤씨(주),298020,2019/12,158.22,338.18,21569.0,453.10,5.40,78.12,359.480,2.000,5.120
2733,효성티앤씨(주),298020,2020/12,-17.45,46.96,31698.0,294.79,5.16,-13.73,10.240,1.375,3.240
2734,효성티앤씨(주),298020,2021/12,434.08,463.14,178503.0,156.66,16.56,66.54,9.165,4.770,12.370
2735,효성티앤씨(주),298020,2022/12,-91.32,-98.50,2686.0,185.04,1.39,3.34,6.485,2.415,7.755

In [321]:
kospii.reset_index(drop=True)

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,1주당순이익,부채비율,매출액정상영업이익률,매출액증가율,PER,PBR,PCR
0,(주)BNK금융지주,138930,2011/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2542,효성티앤씨(주),298020,2018/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2543,효성티앤씨(주),298020,2019/06,551.38,0.00,14680.0,477.87,5.00,530.33,19.220,NaN,7.080
2544,효성티앤씨(주),298020,2020/06,-52.21,-89.17,1590.0,427.40,2.94,-18.63,16.595,NaN,15.940
2545,효성티앤씨(주),298020,2021/06,801.67,5379.39,87118.0,201.77,16.86,57.09,14.075,NaN,15.415
2546,효성티앤씨(주),298020,2022/06,-56.21,-74.84,21917.0,210.84,5.66,30.43,12.450,NaN,0.000

In [322]:
# kospi.to_csv('kospi_사업_결측치존재.csv', encoding='utf-8-sig')

In [323]:
# kospii.to_csv('kospi_반기.csv', encoding='utf-8-sig')