In [1]:
import pandas as pd

In [9]:
kospi1 = pd.read_csv("./1Q.csv", encoding = "utf-8")
kospi2 = pd.read_csv("./kospi_반기.csv", encoding = "utf-8")
kospi3 = pd.read_csv("./3Q.csv", encoding = "utf-8")
kospi4 = pd.read_csv("./kospi_사업.csv", encoding = "utf-8")

In [10]:
kospi1

,Unnamed: 0,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,매출액증가율,주당순손익,부채비율,매출액정상영업이익률
0,0,(주)BNK금융지주,138930,2011,NaN,NaN,NaN,NaN,NaN,NaN
1,1,(주)BNK금융지주,138930,2012,NaN,NaN,NaN,NaN,NaN,NaN
2,2,(주)BNK금융지주,138930,2013,NaN,NaN,NaN,NaN,NaN,NaN
3,3,(주)BNK금융지주,138930,2014,NaN,NaN,NaN,NaN,NaN,NaN
4,4,(주)BNK금융지주,138930,2015,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2515,2515,효성첨단소재(주),298050,2022,5.601108,-6.394356,1.465495,0.0,327.825675,10.131358
2516,2516,효성티앤씨(주),298020,2019,9.895601,468.090109,68.328782,0.0,533.684655,3.879797
2517,2517,효성티앤씨(주),298020,2020,-6.118253,-37.545806,-5.637976,0.0,445.689326,5.656853
2518,2518,효성티앤씨(주),298020,2021,89.694979,62.533317,10.364907,0.0,259.614113,15.251293
2519,2519,효성티앤씨(주),298020,2022,-46.571582,-51.568598,-4.362511,0.0,209.984343,8.122769

In [11]:
kospi2

,Unnamed: 0,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,1주당순이익,부채비율,매출액정상영업이익률,매출액증가율,1주당 CASH FLOW,1주당순자산,PER,PBR,PCR
0,0,(주)BNK금융지주,138930,2011/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,(주)BNK금융지주,138930,2012/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,(주)BNK금융지주,138930,2013/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,(주)BNK금융지주,138930,2014/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,(주)BNK금융지주,138930,2015/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2634,2634,효성티앤씨(주),298020,2018/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2635,2635,효성티앤씨(주),298020,2019/06,551.38,0.00,14680.0,477.87,5.00,530.33,58339.24,NaN,19.220,NaN,7.080
2636,2636,효성티앤씨(주),298020,2020/06,-52.21,-89.17,1590.0,427.40,2.94,-18.63,34001.99,NaN,16.595,NaN,15.940
2637,2637,효성티앤씨(주),298020,2021/06,801.67,5379.39,87118.0,201.77,16.86,57.09,59881.44,NaN,14.075,NaN,15.415
2638,2638,효성티앤씨(주),298020,2022/06,-56.21,-74.84,21917.0,210.84,5.66,30.43,-34291.52,NaN,12.450,NaN,0.000

In [14]:
kospi3.columns

Index(['Unnamed: 0', '회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율',
       '주당순손익', '부채비율', '매출액정상영업이익률'],
      dtype='object')

In [13]:
kospi4

,Unnamed: 0,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,1주당순이익,부채비율,매출액정상영업이익률,매출액증가율,1주당 CASH FLOW,1주당순자산,PER,PBR,PCR
0,0,(주)BNK금융지주,138930,2011/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,(주)BNK금융지주,138930,2012/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,(주)BNK금융지주,138930,2013/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,(주)BNK금융지주,138930,2014/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,(주)BNK금융지주,138930,2015/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2825,2825,효성티앤씨(주),298020,2018/12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2826,2826,효성티앤씨(주),298020,2019/12,158.22,338.18,21569.0,453.10,5.40,78.12,80769.46,81519.29,359.480,2.000,5.120
2827,2827,효성티앤씨(주),298020,2020/12,-17.45,46.96,31698.0,294.79,5.16,-13.73,130512.89,107417.54,10.240,1.375,3.240
2828,2828,효성티앤씨(주),298020,2021/12,434.08,463.14,178503.0,156.66,16.56,66.54,148645.95,122485.93,9.165,4.770,12.370
2829,2829,효성티앤씨(주),298020,2022/12,-91.32,-98.50,2686.0,185.04,1.39,3.34,67792.19,179902.61,6.485,2.415,7.755

In [19]:
kospi2['회계년도'].unique()

array(['2011/06', '2012/06', '2013/06', '2014/06', '2015/06', '2016/06',
       '2017/06', '2018/06', '2019/06', '2020/06', '2021/06', '2022/06',
       '2007/06', '2008/06', '2009/06', '2010/06', '2007/09', '2008/09',
       '2009/09', '2010/09', '2011/09', '2012/09', '2013/09'],
      dtype=object)

In [20]:
kospi2 = kospi2[~kospi2['회계년도'].str.endswith('/09')]

In [21]:
kospi2['회계년도'].unique()

array(['2011/06', '2012/06', '2013/06', '2014/06', '2015/06', '2016/06',
       '2017/06', '2018/06', '2019/06', '2020/06', '2021/06', '2022/06',
       '2007/06', '2008/06', '2009/06', '2010/06'], dtype=object)

In [23]:
kospi2['회계년도'] = kospi2['회계년도'].str.replace('/06', '')

/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/4100027477.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi2['회계년도'] = kospi2['회계년도'].str.replace('/06', '')

In [27]:
kospi2_ = kospi2[['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율']]

In [26]:
kospi3_ = kospi3[['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율']]

In [32]:
kospi2_.reset_index(drop=True, inplace=True)
kospi3_.reset_index(drop=True, inplace=True)

In [33]:
kospi2_

             회사명   거래소코드  회계년도  정상영업이익증가율   순이익증가율  매출액증가율
0     (주)BNK금융지주  138930  2011        NaN      NaN     NaN
1     (주)BNK금융지주  138930  2012        NaN      NaN     NaN
2     (주)BNK금융지주  138930  2013        NaN      NaN     NaN
3     (주)BNK금융지주  138930  2014        NaN      NaN     NaN
4     (주)BNK금융지주  138930  2015        NaN      NaN     NaN
...          ...     ...   ...        ...      ...     ...
2542    효성티앤씨(주)  298020  2018        NaN      NaN     NaN
2543    효성티앤씨(주)  298020  2019     551.38     0.00  530.33
2544    효성티앤씨(주)  298020  2020     -52.21   -89.17  -18.63
2545    효성티앤씨(주)  298020  2021     801.67  5379.39   57.09
2546    효성티앤씨(주)  298020  2022     -56.21   -74.84   30.43

[2547 rows x 6 columns]

In [34]:
kospi3_

             회사명   거래소코드  회계년도   정상영업이익증가율      순이익증가율     매출액증가율
0     (주)BNK금융지주  138930  2011         NaN         NaN        NaN
1     (주)BNK금융지주  138930  2012         NaN         NaN        NaN
2     (주)BNK금융지주  138930  2013         NaN         NaN        NaN
3     (주)BNK금융지주  138930  2014         NaN         NaN        NaN
4     (주)BNK금융지주  138930  2015         NaN         NaN        NaN
...          ...     ...   ...         ...         ...        ...
2515   효성첨단소재(주)  298050  2022  -32.296112  -55.155613  -4.830042
2516    효성티앤씨(주)  298020  2019   -0.195735 -102.126905   2.584437
2517    효성티앤씨(주)  298020  2020 -906.766857 -359.566441  29.412725
2518    효성티앤씨(주)  298020  2021   12.101227    3.703581  11.491809
2519    효성티앤씨(주)  298020  2022 -226.688224 -384.848013 -15.470640

[2520 rows x 6 columns]

In [38]:
kospi3_['회계년도'] = kospi3_['회계년도'].astype(str)
kospi2_['회계년도'] = kospi2_['회계년도'].astype(str)
kospi3_['회사명'] = kospi3_['회사명'].astype(str)
kospi2_['회사명'] = kospi2_['회사명'].astype(str)
kospi3_['거래소코드'] = kospi3_['거래소코드'].astype(str)
kospi2_['거래소코드'] = kospi2_['거래소코드'].astype(str)

/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/4170203477.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi3_['회계년도'] = kospi3_['회계년도'].astype(str)
/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/4170203477.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi2_['회계년도'] = kospi2_['회계년도'].astype(str)
/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/4170203477.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi3_['회사명'] = kospi3_['회사명'].astype(str)
/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/4170203477.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi2_['회사명'] = kospi2_['회사명'].astype(str)
/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/4170203477.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi3_['거래소코드'] = kospi3_['거래소코드'].astype(str)
/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/4170203477.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi2_['거래소코드'] = kospi2_['거래소코드'].astype(str)

In [39]:
k_3 = pd.DataFrame(columns=kospi2_.columns)  # 빈 데이터프레임 생성
k_3_ = pd.DataFrame(columns=kospi3_.columns)  # 빈 데이터프레임 생성

for i in range(len(kospi2_)):
    for j in range(len(kospi3_)):
        if (kospi2_.loc[i, '회사명'] == kospi3_.loc[j, '회사명'] and
            kospi2_.loc[i, '거래소코드'] == kospi3_.loc[j, '거래소코드'] and
            kospi2_.loc[i, '회계년도'] == kospi3_.loc[j, '회계년도']):
            k_3 = pd.concat([k_3, kospi2_.loc[[i]]], ignore_index=True)
            k_3_ = pd.concat([k_3_, kospi3_.loc[[j]]], ignore_index=True)
            break

In [40]:
k_3

             회사명   거래소코드  회계년도  정상영업이익증가율   순이익증가율  매출액증가율
0     (주)BNK금융지주  138930  2011        NaN      NaN     NaN
1     (주)BNK금융지주  138930  2012        NaN      NaN     NaN
2     (주)BNK금융지주  138930  2013        NaN      NaN     NaN
3     (주)BNK금융지주  138930  2014        NaN      NaN     NaN
4     (주)BNK금융지주  138930  2015        NaN      NaN     NaN
...          ...     ...   ...        ...      ...     ...
2515   효성첨단소재(주)  298050  2022      -0.99   -13.79   23.53
2516    효성티앤씨(주)  298020  2019     551.38     0.00  530.33
2517    효성티앤씨(주)  298020  2020     -52.21   -89.17  -18.63
2518    효성티앤씨(주)  298020  2021     801.67  5379.39   57.09
2519    효성티앤씨(주)  298020  2022     -56.21   -74.84   30.43

[2520 rows x 6 columns]

In [41]:
k_3_

             회사명   거래소코드  회계년도   정상영업이익증가율      순이익증가율     매출액증가율
0     (주)BNK금융지주  138930  2011         NaN         NaN        NaN
1     (주)BNK금융지주  138930  2012         NaN         NaN        NaN
2     (주)BNK금융지주  138930  2013         NaN         NaN        NaN
3     (주)BNK금융지주  138930  2014         NaN         NaN        NaN
4     (주)BNK금융지주  138930  2015         NaN         NaN        NaN
...          ...     ...   ...         ...         ...        ...
2515   효성첨단소재(주)  298050  2022  -32.296112  -55.155613  -4.830042
2516    효성티앤씨(주)  298020  2019   -0.195735 -102.126905   2.584437
2517    효성티앤씨(주)  298020  2020 -906.766857 -359.566441  29.412725
2518    효성티앤씨(주)  298020  2021   12.101227    3.703581  11.491809
2519    효성티앤씨(주)  298020  2022 -226.688224 -384.848013 -15.470640

[2520 rows x 6 columns]

In [43]:
k_3_['정상영업이익증가율'] = k_3['정상영업이익증가율'] + k_3_['정상영업이익증가율']
k_3_['순이익증가율'] = k_3['순이익증가율'] + k_3_['순이익증가율']
k_3_['매출액증가율'] = k_3['매출액증가율'] + k_3_['매출액증가율']

In [44]:
k_3_

             회사명   거래소코드  회계년도   정상영업이익증가율       순이익증가율      매출액증가율
0     (주)BNK금융지주  138930  2011         NaN          NaN         NaN
1     (주)BNK금융지주  138930  2012         NaN          NaN         NaN
2     (주)BNK금융지주  138930  2013         NaN          NaN         NaN
3     (주)BNK금융지주  138930  2014         NaN          NaN         NaN
4     (주)BNK금융지주  138930  2015         NaN          NaN         NaN
...          ...     ...   ...         ...          ...         ...
2515   효성첨단소재(주)  298050  2022  -33.286112   -68.945613   18.699958
2516    효성티앤씨(주)  298020  2019  551.184265  -102.126905  532.914437
2517    효성티앤씨(주)  298020  2020 -958.976857  -448.736441   10.782725
2518    효성티앤씨(주)  298020  2021  813.771227  5383.093581   68.581809
2519    효성티앤씨(주)  298020  2022 -282.898224  -459.688013   14.959360

[2520 rows x 6 columns]

In [46]:
kospi3 = pd.concat([k_3_[['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율']], kospi3[['주당순손익', '부채비율', '매출액정상영업이익률']]], axis=1)

In [47]:
kospi3

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,매출액증가율,주당순손익,부채비율,매출액정상영업이익률
0,(주)BNK금융지주,138930,2011,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2515,효성첨단소재(주),298050,2022,-33.286112,-68.945613,18.699958,0.0,291.193755,8.832273
2516,효성티앤씨(주),298020,2019,551.184265,-102.126905,532.914437,0.0,505.570765,5.302956
2517,효성티앤씨(주),298020,2020,-958.976857,-448.736441,10.782725,0.0,368.127280,3.692649
2518,효성티앤씨(주),298020,2021,813.771227,5383.093581,68.581809,0.0,165.909917,17.366611
2519,효성티앤씨(주),298020,2022,-282.898224,-459.688013,14.959360,0.0,209.447660,2.358745

In [54]:
kospi3.columns = ['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율', '1주당순이익', '부채비율', '매출액정상영업이익률']

In [57]:
kospi4 = kospi4[['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율', '1주당순이익', '부채비율', '매출액정상영업이익률']]

In [59]:
kospi3['회계년도'] = kospi3['회계년도'].astype(str)
kospi4['회계년도'] = kospi4['회계년도'].astype(str)
kospi3['회사명'] = kospi3['회사명'].astype(str)
kospi4['회사명'] = kospi4['회사명'].astype(str)
kospi3['거래소코드'] = kospi3['거래소코드'].astype(str)
kospi4['거래소코드'] = kospi4['거래소코드'].astype(str)

/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/755994717.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi4['회계년도'] = kospi4['회계년도'].astype(str)
/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/755994717.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi4['회사명'] = kospi4['회사명'].astype(str)
/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/755994717.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi4['거래소코드'] = kospi4['거래소코드'].astype(str)

In [63]:
kospi3

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,매출액증가율,1주당순이익,부채비율,매출액정상영업이익률
0,(주)BNK금융지주,138930,2011,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2515,효성첨단소재(주),298050,2022,-33.286112,-68.945613,18.699958,0.0,291.193755,8.832273
2516,효성티앤씨(주),298020,2019,551.184265,-102.126905,532.914437,0.0,505.570765,5.302956
2517,효성티앤씨(주),298020,2020,-958.976857,-448.736441,10.782725,0.0,368.127280,3.692649
2518,효성티앤씨(주),298020,2021,813.771227,5383.093581,68.581809,0.0,165.909917,17.366611
2519,효성티앤씨(주),298020,2022,-282.898224,-459.688013,14.959360,0.0,209.447660,2.358745

In [64]:
kospi4

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,매출액증가율,1주당순이익,부채비율,매출액정상영업이익률
0,(주)BNK금융지주,138930,2011/12,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012/12,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013/12,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014/12,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015/12,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2825,효성티앤씨(주),298020,2018/12,NaN,NaN,NaN,NaN,NaN,NaN
2826,효성티앤씨(주),298020,2019/12,158.22,338.18,78.12,21569.0,453.10,5.40
2827,효성티앤씨(주),298020,2020/12,-17.45,46.96,-13.73,31698.0,294.79,5.16
2828,효성티앤씨(주),298020,2021/12,434.08,463.14,66.54,178503.0,156.66,16.56
2829,효성티앤씨(주),298020,2022/12,-91.32,-98.50,3.34,2686.0,185.04,1.39

In [68]:
kospi4['회계년도'].unique()

array(['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022', '2007', '2008', '2009', '2010'],
      dtype=object)

In [66]:
kospi4 = kospi4[~kospi4['회계년도'].str.endswith('/03')]

In [67]:
kospi4['회계년도'] = kospi4['회계년도'].str.replace('/12', '')

/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/1972405715.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi4['회계년도'] = kospi4['회계년도'].str.replace('/12', '')

In [70]:
kospi3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2520 entries, 0 to 2519
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   회사명         2520 non-null   object
 1   거래소코드       2520 non-null   object
 2   회계년도        2520 non-null   object
 3   정상영업이익증가율   2277 non-null   float64
 4   순이익증가율      2277 non-null   float64
 5   매출액증가율      2277 non-null   float64
 6   1주당순이익      2306 non-null   float64
 7   부채비율        2306 non-null   float64
 8   매출액정상영업이익률  2306 non-null   float64
dtypes: float64(6), object(3)
memory usage: 177.3+ KB

In [74]:
kospi3.reset_index(drop=True, inplace=True)

In [75]:
kospi4.reset_index(drop=True, inplace=True)

In [76]:
k3 = pd.DataFrame(columns=kospi3.columns)  # 빈 데이터프레임 생성
k4 = pd.DataFrame(columns=kospi4.columns)  # 빈 데이터프레임 생성

for i in range(len(kospi3)):
    for j in range(len(kospi4)):
        if (kospi3.loc[i, '회사명'] == kospi4.loc[j, '회사명'] and
            kospi3.loc[i, '거래소코드'] == kospi4.loc[j, '거래소코드'] and
            kospi3.loc[i, '회계년도'] == kospi4.loc[j, '회계년도']):
            k3 = pd.concat([k3, kospi3.loc[[i]]], ignore_index=True)
            k4 = pd.concat([k4, kospi4.loc[[j]]], ignore_index=True)
            break

In [78]:
k4

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,매출액증가율,1주당순이익,부채비율,매출액정상영업이익률
0,(주)BNK금융지주,138930,2011,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2515,효성첨단소재(주),298050,2022,-27.95,-50.00,6.77,28053.0,267.04,8.20
2516,효성티앤씨(주),298020,2019,158.22,338.18,78.12,21569.0,453.10,5.40
2517,효성티앤씨(주),298020,2020,-17.45,46.96,-13.73,31698.0,294.79,5.16
2518,효성티앤씨(주),298020,2021,434.08,463.14,66.54,178503.0,156.66,16.56
2519,효성티앤씨(주),298020,2022,-91.32,-98.50,3.34,2686.0,185.04,1.39

In [79]:
k4['정상영업이익증가율'] = k4['정상영업이익증가율'] - k3['정상영업이익증가율']
k4['순이익증가율'] = k4['순이익증가율'] - k3['순이익증가율']
k4['매출액증가율'] = k4['매출액증가율'] - k3['매출액증가율']
k4['1주당순이익'] = k4['1주당순이익'] - k3['1주당순이익']
k4['부채비율'] = k4['부채비율'] - k3['부채비율']
k4['매출액정상영업이익률'] = k4['매출액정상영업이익률'] - k3['매출액정상영업이익률']

In [80]:
k4

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,매출액증가율,1주당순이익,부채비율,매출액정상영업이익률
0,(주)BNK금융지주,138930,2011,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2515,효성첨단소재(주),298050,2022,5.336112,18.945613,-11.929958,28053.0,-24.153755,-0.632273
2516,효성티앤씨(주),298020,2019,-392.964265,440.306905,-454.794437,21569.0,-52.470765,0.097044
2517,효성티앤씨(주),298020,2020,941.526857,495.696441,-24.512725,31698.0,-73.337280,1.467351
2518,효성티앤씨(주),298020,2021,-379.691227,-4919.953581,-2.041809,178503.0,-9.249917,-0.806611
2519,효성티앤씨(주),298020,2022,191.578224,361.188013,-11.619360,2686.0,-24.407660,-0.968745

In [82]:
k4.to_csv('Q4.csv', encoding='utf-8-sig')

In [83]:
kospi2['회계년도'].unique()

array(['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022', '2007', '2008', '2009', '2010'],
      dtype=object)

In [84]:
kospi2.columns

Index(['Unnamed: 0', '회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '1주당순이익',
       '부채비율', '매출액정상영업이익률', '매출액증가율', '1주당 CASH FLOW', '1주당순자산', 'PER', 'PBR',
       'PCR'],
      dtype='object')

In [85]:
kospi3.columns

Index(['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율', '1주당순이익',
       '부채비율', '매출액정상영업이익률'],
      dtype='object')

In [86]:
kospi2 = kospi2[['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율', '1주당순이익', '부채비율', '매출액정상영업이익률']]

In [87]:
kospi3

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,매출액증가율,1주당순이익,부채비율,매출액정상영업이익률
0,(주)BNK금융지주,138930,2011,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2515,효성첨단소재(주),298050,2022,-33.286112,-68.945613,18.699958,0.0,291.193755,8.832273
2516,효성티앤씨(주),298020,2019,551.184265,-102.126905,532.914437,0.0,505.570765,5.302956
2517,효성티앤씨(주),298020,2020,-958.976857,-448.736441,10.782725,0.0,368.127280,3.692649
2518,효성티앤씨(주),298020,2021,813.771227,5383.093581,68.581809,0.0,165.909917,17.366611
2519,효성티앤씨(주),298020,2022,-282.898224,-459.688013,14.959360,0.0,209.447660,2.358745

In [88]:
kospi3['회계년도'] = kospi3['회계년도'].astype(str)
kospi2['회계년도'] = kospi2['회계년도'].astype(str)
kospi3['회사명'] = kospi3['회사명'].astype(str)
kospi2['회사명'] = kospi2['회사명'].astype(str)
kospi3['거래소코드'] = kospi3['거래소코드'].astype(str)
kospi2['거래소코드'] = kospi2['거래소코드'].astype(str)

/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/3080594462.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi2['회계년도'] = kospi2['회계년도'].astype(str)
/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/3080594462.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi2['회사명'] = kospi2['회사명'].astype(str)
/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/3080594462.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi2['거래소코드'] = kospi2['거래소코드'].astype(str)

In [89]:
kospi3.reset_index(drop=True, inplace=True)
kospi2.reset_index(drop=True, inplace=True)

In [90]:
k2_ = pd.DataFrame(columns=kospi2.columns)  # 빈 데이터프레임 생성
k3_ = pd.DataFrame(columns=kospi3.columns)  # 빈 데이터프레임 생성

for i in range(len(kospi2)):
    for j in range(len(kospi3)):
        if (kospi2.loc[i, '회사명'] == kospi3.loc[j, '회사명'] and
            kospi2.loc[i, '거래소코드'] == kospi3.loc[j, '거래소코드'] and
            kospi2.loc[i, '회계년도'] == kospi3.loc[j, '회계년도']):
            k2_ = pd.concat([k2_, kospi2.loc[[i]]], ignore_index=True)
            k3_ = pd.concat([k3_, kospi3.loc[[j]]], ignore_index=True)
            break

In [93]:
k3_['정상영업이익증가율'] = k3_['정상영업이익증가율'] - k2_['정상영업이익증가율']
k3_['순이익증가율'] = k3_['순이익증가율'] - k2_['순이익증가율']
k3_['매출액증가율'] = k3_['매출액증가율'] - k2_['매출액증가율']
k3_['1주당순이익'] = k3_['1주당순이익'] - k2_['1주당순이익']
k3_['부채비율'] = k3_['부채비율'] - k2_['부채비율']
k3_['매출액정상영업이익률'] = k3_['매출액정상영업이익률'] - k2_['매출액정상영업이익률']

In [94]:
k3_

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,매출액증가율,1주당순이익,부채비율,매출액정상영업이익률
0,(주)BNK금융지주,138930,2011,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2515,효성첨단소재(주),298050,2022,-32.296112,-55.155613,-4.830042,-22747.0,-18.876245,-0.987727
2516,효성티앤씨(주),298020,2019,-0.195735,-102.126905,2.584437,-14680.0,27.700765,0.302956
2517,효성티앤씨(주),298020,2020,-906.766857,-359.566441,29.412725,-1590.0,-59.272720,0.752649
2518,효성티앤씨(주),298020,2021,12.101227,3.703581,11.491809,-87118.0,-35.860083,0.506611
2519,효성티앤씨(주),298020,2022,-226.688224,-384.848013,-15.470640,-21917.0,-1.392340,-3.301255

In [95]:
k3_.to_csv('Q3.csv', encoding='utf-8-sig')

array(['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022', '2007', '2008', '2009', '2010'],
      dtype=object)

In [98]:
kospi1.columns

Index(['Unnamed: 0', '회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율',
       '주당순손익', '부채비율', '매출액정상영업이익률'],
      dtype='object')

In [100]:
kospi1.columns = ['Unnamed: 0', '회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율', '1주당순이익', '부채비율', '매출액정상영업이익률']

In [101]:
kospi1 = kospi1[['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율', '1주당순이익', '부채비율', '매출액정상영업이익률']]

In [99]:
kospi2.columns

Index(['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율', '1주당순이익',
       '부채비율', '매출액정상영업이익률'],
      dtype='object')

In [102]:
kospi2 = kospi2[['회사명', '거래소코드', '회계년도', '정상영업이익증가율', '순이익증가율', '매출액증가율', '1주당순이익', '부채비율', '매출액정상영업이익률']]

In [103]:
kospi2

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,매출액증가율,1주당순이익,부채비율,매출액정상영업이익률
0,(주)BNK금융지주,138930,2011,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2542,효성티앤씨(주),298020,2018,NaN,NaN,NaN,NaN,NaN,NaN
2543,효성티앤씨(주),298020,2019,551.38,0.00,530.33,14680.0,477.87,5.00
2544,효성티앤씨(주),298020,2020,-52.21,-89.17,-18.63,1590.0,427.40,2.94
2545,효성티앤씨(주),298020,2021,801.67,5379.39,57.09,87118.0,201.77,16.86
2546,효성티앤씨(주),298020,2022,-56.21,-74.84,30.43,21917.0,210.84,5.66

In [104]:
kospi1

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,매출액증가율,1주당순이익,부채비율,매출액정상영업이익률
0,(주)BNK금융지주,138930,2011,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2515,효성첨단소재(주),298050,2022,5.601108,-6.394356,1.465495,0.0,327.825675,10.131358
2516,효성티앤씨(주),298020,2019,9.895601,468.090109,68.328782,0.0,533.684655,3.879797
2517,효성티앤씨(주),298020,2020,-6.118253,-37.545806,-5.637976,0.0,445.689326,5.656853
2518,효성티앤씨(주),298020,2021,89.694979,62.533317,10.364907,0.0,259.614113,15.251293
2519,효성티앤씨(주),298020,2022,-46.571582,-51.568598,-4.362511,0.0,209.984343,8.122769

In [105]:
kospi1['회계년도'] = kospi1['회계년도'].astype(str)
kospi2['회계년도'] = kospi2['회계년도'].astype(str)
kospi1['회사명'] = kospi1['회사명'].astype(str)
kospi2['회사명'] = kospi2['회사명'].astype(str)
kospi1['거래소코드'] = kospi1['거래소코드'].astype(str)
kospi2['거래소코드'] = kospi2['거래소코드'].astype(str)

/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/4084113171.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi1['회계년도'] = kospi1['회계년도'].astype(str)
/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/4084113171.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi1['회사명'] = kospi1['회사명'].astype(str)
/var/folders/xs/8nhrbkk97jzf2f4zjswkk0b80000gn/T/ipykernel_6044/4084113171.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi1['거래소코드'] = kospi1['거래소코드'].astype(str)

In [106]:
kospi1.reset_index(drop=True, inplace=True)
kospi2.reset_index(drop=True, inplace=True)

In [107]:
k1_ = pd.DataFrame(columns=kospi1.columns)  # 빈 데이터프레임 생성
k2 = pd.DataFrame(columns=kospi2.columns)  # 빈 데이터프레임 생성

for i in range(len(kospi1)):
    for j in range(len(kospi2)):
        if (kospi1.loc[i, '회사명'] == kospi2.loc[j, '회사명'] and
            kospi1.loc[i, '거래소코드'] == kospi2.loc[j, '거래소코드'] and
            kospi1.loc[i, '회계년도'] == kospi2.loc[j, '회계년도']):
            k1_ = pd.concat([k1_, kospi1.loc[[i]]], ignore_index=True)
            k2 = pd.concat([k2, kospi2.loc[[j]]], ignore_index=True)
            break

In [110]:
k1_

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,매출액증가율,1주당순이익,부채비율,매출액정상영업이익률
0,(주)BNK금융지주,138930,2011,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2515,효성첨단소재(주),298050,2022,5.601108,-6.394356,1.465495,0.0,327.825675,10.131358
2516,효성티앤씨(주),298020,2019,9.895601,468.090109,68.328782,0.0,533.684655,3.879797
2517,효성티앤씨(주),298020,2020,-6.118253,-37.545806,-5.637976,0.0,445.689326,5.656853
2518,효성티앤씨(주),298020,2021,89.694979,62.533317,10.364907,0.0,259.614113,15.251293
2519,효성티앤씨(주),298020,2022,-46.571582,-51.568598,-4.362511,0.0,209.984343,8.122769

In [111]:
k2['정상영업이익증가율'] = k2['정상영업이익증가율'] - k1_['정상영업이익증가율']
k2['순이익증가율'] = k2['순이익증가율'] - k1_['순이익증가율']
k2['매출액증가율'] = k2['매출액증가율'] - k1_['매출액증가율']
k2['1주당순이익'] = k2['1주당순이익'] - k1_['1주당순이익']
k2['부채비율'] = k2['부채비율'] - k1_['부채비율']
k2['매출액정상영업이익률'] = k2['매출액정상영업이익률'] - k1_['매출액정상영업이익률']

In [112]:
k2

,회사명,거래소코드,회계년도,정상영업이익증가율,순이익증가율,매출액증가율,1주당순이익,부채비율,매출액정상영업이익률
0,(주)BNK금융지주,138930,2011,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2012,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2014,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2015,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2515,효성첨단소재(주),298050,2022,-6.591108,-7.395644,22.064505,22747.0,-17.755675,-0.311358
2516,효성티앤씨(주),298020,2019,541.484399,-468.090109,462.001218,14680.0,-55.814655,1.120203
2517,효성티앤씨(주),298020,2020,-46.091747,-51.624194,-12.992024,1590.0,-18.289326,-2.716853
2518,효성티앤씨(주),298020,2021,711.975021,5316.856683,46.725093,87118.0,-57.844113,1.608707
2519,효성티앤씨(주),298020,2022,-9.638418,-23.271402,34.792511,21917.0,0.855657,-2.462769

In [113]:
k2.to_csv('Q2.csv', encoding='utf-8-sig')

In [114]:
k1_.to_csv('Q1.csv', encoding='utf-8-sig')