In [14]:
# 크롤링할때 필요한 라이브러리
import requests
from bs4 import BeautifulSoup as bs

In [15]:
# 크롤링 할때 get()사용 : 주어진 URL에서 HTML 페이지를 가져옵니다
requests.get('https://finance.naver.com/marketindex/exchangeList.naver')
# 결과 <Response [200]> : 정상적이다

In [16]:
# 실제 사이트에서 html 정보를 받아와서 변수에 저장
data = requests.get('https://finance.naver.com/marketindex/exchangeList.naver').text

In [17]:
# BeautifulSoup을 이용하여 데이터를 파싱
soup = bs(data, 'html.parser')

In [18]:
print(soup)

<html lang="ko">
<head>
<title>네이버 증권</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="text/javascript" http-equiv="Content-Script-Type"/>
<meta content="text/css" http-equiv="Content-Style-Type"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/finance.css" rel="stylesheet" type="text/css"/>
<script language="javascript">document.domain="naver.com";</script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/js/info/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/js/lcslog.js" type="text/javascript"></script>
</head>
<body>
<div class="tbl_area">
<table border="1" class="tbl_exchange" summary="환전 고시 환율 리스트">
<caption>환전 고시 환율</caption>
<colgroup>
<col width="162"/>
<col width="92"/>
<col width="92"/>
<col width="92"/>
<col width="93"/>
<col width="92"/>
<col width="90"/>
</colgroup>
<thead>
<tr>
<th class="th_ex1" rowspan="2">
<a href="#" onclick="javascript:changeOrder('exchange'); return false;"><span>통화명</span></a></th>
<th class="th_ex2" rowspan="2"><span>매매기준율</span></th>
<th class="th_ex3" colspan="2"><span>현찰</span></th>
<th class="th_ex4" colspan="2"><span>송금</span></th>
<th class="th_ex6" rowspan="2"><span>미화환산율</span></th>
</tr>
<tr>
<th class="th_ex7"><span>사실 때 </span></th>
<th class="th_ex8"><span>파실 때 </span></th>
<th class="th_ex9"><span>보내실 때 </span></th>
<th class="th_ex10"><span>받으실 때</span></th>
</tr>
</thead>
<tbody>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_USDKRW', '1', event);" target="_parent">




					미국 USD

				</a></td>
<td class="sale">1,316.30</td>
<td>


						1,339.33

				</td>
<td>


						1,293.27

				</td>
<td>


						1,329.10

				</td>
<td>


						1,303.50

				</td>
<td>1.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EURKRW', '2', event);" target="_parent">




					유럽연합 EUR

				</a></td>
<td class="sale">1,445.17</td>
<td>


						1,473.92

				</td>
<td>


						1,416.42

				</td>
<td>


						1,459.62

				</td>
<td>


						1,430.72

				</td>
<td>1.098</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JPYKRW', '3', event);" target="_parent">

					일본 JPY (100엔)




				</a></td>
<td class="sale">981.69</td>
<td>


						998.86

				</td>
<td>


						964.52

				</td>
<td>


						991.31

				</td>
<td>


						972.07

				</td>
<td>0.746</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CNYKRW', '4', event);" target="_parent">




					중국 CNY

				</a></td>
<td class="sale">191.41</td>
<td>


						200.98

				</td>
<td>


						181.84

				</td>
<td>


						193.32

				</td>
<td>


						189.50

				</td>
<td>0.145</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HKDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HKDKRW', '5', event);" target="_parent">




					홍콩 HKD

				</a></td>
<td class="sale">167.72</td>
<td>


						171.02

				</td>
<td>


						164.42

				</td>
<td>


						169.39

				</td>
<td>


						166.05

				</td>
<td>0.127</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TWDKRW', '6', event);" target="_parent">




					대만 TWD

				</a></td>
<td class="sale">43.16</td>
<td>


						48.81

				</td>
<td>


						38.85

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.033</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_GBPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_GBPKRW', '7', event);" target="_parent">




					영국 GBP

				</a></td>
<td class="sale">1,635.77</td>
<td>


						1,667.99

				</td>
<td>


						1,603.55

				</td>
<td>


						1,652.12

				</td>
<td>


						1,619.42

				</td>
<td>1.243</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_OMRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_OMRKRW', '8', event);" target="_parent">




					오만 OMR

				</a></td>
<td class="sale">3,418.78</td>
<td>


						3,723.05

				</td>
<td>


						3,213.66

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>2.597</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CADKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CADKRW', '9', event);" target="_parent">




					캐나다 CAD

				</a></td>
<td class="sale">982.94</td>
<td>


						1,002.30

				</td>
<td>


						963.58

				</td>
<td>


						992.76

				</td>
<td>


						973.12

				</td>
<td>0.747</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CHFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CHFKRW', '10', event);" target="_parent">




					스위스 CHF

				</a></td>
<td class="sale">1,468.76</td>
<td>


						1,497.69

				</td>
<td>


						1,439.83

				</td>
<td>


						1,483.44

				</td>
<td>


						1,454.08

				</td>
<td>1.116</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SEKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SEKKRW', '11', event);" target="_parent">




					스웨덴 SEK

				</a></td>
<td class="sale">127.68</td>
<td>


						130.80

				</td>
<td>


						124.56

				</td>
<td>


						128.95

				</td>
<td>


						126.41

				</td>
<td>0.097</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AUDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AUDKRW', '12', event);" target="_parent">




					호주 AUD

				</a></td>
<td class="sale">886.33</td>
<td>


						903.79

				</td>
<td>


						868.87

				</td>
<td>


						895.19

				</td>
<td>


						877.47

				</td>
<td>0.673</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NZDKRW', '13', event);" target="_parent">




					뉴질랜드 NZD

				</a></td>
<td class="sale">817.42</td>
<td>


						833.52

				</td>
<td>


						801.32

				</td>
<td>


						825.59

				</td>
<td>


						809.25

				</td>
<td>0.621</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CZKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CZKKRW', '14', event);" target="_parent">




					체코 CZK

				</a></td>
<td class="sale">61.64</td>
<td>


						66.87

				</td>
<td>


						56.10

				</td>
<td>


						62.31

				</td>
<td>


						60.97

				</td>
<td>0.047</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CLPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CLPKRW', '15', event);" target="_parent">




					칠레 CLP

				</a></td>
<td class="sale">1.66</td>
<td>


						1.82

				</td>
<td>


						1.50

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.001</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TRYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TRYKRW', '16', event);" target="_parent">




					튀르키예 TRY

				</a></td>
<td class="sale">67.86</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						68.60

				</td>
<td>


						67.12

				</td>
<td>0.052</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MNTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MNTKRW', '17', event);" target="_parent">




					몽골 MNT

				</a></td>
<td class="sale">0.38</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ILSKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ILSKRW', '18', event);" target="_parent">




					이스라엘 ILS

				</a></td>
<td class="sale">360.86</td>
<td>


						396.94

				</td>
<td>


						332.00

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.274</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DKKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DKKKRW', '19', event);" target="_parent">




					덴마크 DKK

				</a></td>
<td class="sale">193.94</td>
<td>


						198.69

				</td>
<td>


						189.19

				</td>
<td>


						195.87

				</td>
<td>


						192.01

				</td>
<td>0.147</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NOKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NOKKRW', '20', event);" target="_parent">




					노르웨이 NOK

				</a></td>
<td class="sale">125.66</td>
<td>


						128.73

				</td>
<td>


						122.59

				</td>
<td>


						126.91

				</td>
<td>


						124.41

				</td>
<td>0.096</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SARKRW', '21', event);" target="_parent">




					사우디아라비아 SAR

				</a></td>
<td class="sale">350.94</td>
<td>


						373.04

				</td>
<td>


						326.73

				</td>
<td>


						354.44

				</td>
<td>


						347.44

				</td>
<td>0.267</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KWDKRW', '22', event);" target="_parent">




					쿠웨이트 KWD

				</a></td>
<td class="sale">4,295.46</td>
<td>


						4,574.66

				</td>
<td>


						3,951.83

				</td>
<td>


						4,338.41

				</td>
<td>


						4,252.51

				</td>
<td>3.263</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BHDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BHDKRW', '23', event);" target="_parent">




					바레인 BHD

				</a></td>
<td class="sale">3,491.23</td>
<td>


						3,714.66

				</td>
<td>


						3,211.94

				</td>
<td>


						3,526.14

				</td>
<td>


						3,456.32

				</td>
<td>2.652</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AEDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AEDKRW', '24', event);" target="_parent">




					아랍에미리트 AED

				</a></td>
<td class="sale">358.43</td>
<td>


						378.14

				</td>
<td>


						333.70

				</td>
<td>


						362.01

				</td>
<td>


						354.85

				</td>
<td>0.272</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JODKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JODKRW', '25', event);" target="_parent">




					요르단 JOD

				</a></td>
<td class="sale">1,855.51</td>
<td>


						2,020.65

				</td>
<td>


						1,707.07

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>1.410</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EGPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EGPKRW', '26', event);" target="_parent">




					이집트 EGP

				</a></td>
<td class="sale">42.60</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.032</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_THBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_THBKRW', '27', event);" target="_parent">




					태국 THB

				</a></td>
<td class="sale">38.43</td>
<td>


						40.35

				</td>
<td>


						36.13

				</td>
<td>


						38.81

				</td>
<td>


						38.05

				</td>
<td>0.029</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SGDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SGDKRW', '28', event);" target="_parent">




					싱가포르 SGD

				</a></td>
<td class="sale">987.95</td>
<td>


						1,007.61

				</td>
<td>


						968.29

				</td>
<td>


						997.82

				</td>
<td>


						978.08

				</td>
<td>0.751</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MYRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MYRKRW', '29', event);" target="_parent">




					말레이시아 MYR

				</a></td>
<td class="sale">296.97</td>
<td>


						315.67

				</td>
<td>


						275.00

				</td>
<td>

						N/A


				</td>
<td>


						294.01

				</td>
<td>0.226</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_IDRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_IDRKRW', '30', event);" target="_parent">


					인도네시아 IDR 100



				</a></td>
<td class="sale">8.89</td>
<td>


						9.77

				</td>
<td>


						8.01

				</td>
<td>


						8.97

				</td>
<td>


						8.81

				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_QARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_QARKRW', '31', event);" target="_parent">




					카타르 QAR

				</a></td>
<td class="sale">360.81</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.274</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KZTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KZTKRW', '32', event);" target="_parent">




					카자흐스탄 KZT

				</a></td>
<td class="sale">2.91</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.002</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BNDKRW', '33', event);" target="_parent">




					브루나이 BND

				</a></td>
<td class="sale">987.95</td>
<td>


						1,027.46

				</td>
<td>


						928.68

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.751</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_INRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_INRKRW', '34', event);" target="_parent">




					인도 INR

				</a></td>
<td class="sale">16.03</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.012</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PKRKRW', '35', event);" target="_parent">




					파키스탄 PKR

				</a></td>
<td class="sale">4.64</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BDTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BDTKRW', '36', event);" target="_parent">




					방글라데시 BDT

				</a></td>
<td class="sale">12.40</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.009</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PHPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PHPKRW', '37', event);" target="_parent">




					필리핀 PHP

				</a></td>
<td class="sale">23.53</td>
<td>


						25.88

				</td>
<td>


						21.61

				</td>
<td>


						23.76

				</td>
<td>


						23.30

				</td>
<td>0.018</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MXNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MXNKRW', '38', event);" target="_parent">




					멕시코 MXN

				</a></td>
<td class="sale">72.93</td>
<td>


						80.22

				</td>
<td>


						66.81

				</td>
<td>


						73.65

				</td>
<td>


						72.21

				</td>
<td>0.055</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BRLKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BRLKRW', '39', event);" target="_parent">




					브라질 BRL

				</a></td>
<td class="sale">264.00</td>
<td>


						290.92

				</td>
<td>


						237.60

				</td>
<td>

						N/A


				</td>
<td>


						260.84

				</td>
<td>0.201</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_VNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_VNDKRW', '40', event);" target="_parent">



					베트남 VND 100


				</a></td>
<td class="sale">5.60</td>
<td>


						6.26

				</td>
<td>


						4.94

				</td>
<td>


						5.65

				</td>
<td>


						5.55

				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ZARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ZARKRW', '41', event);" target="_parent">




					남아프리카 공화국 ZAR

				</a></td>
<td class="sale">72.45</td>
<td>


						78.24

				</td>
<td>


						66.66

				</td>
<td>


						73.31

				</td>
<td>


						71.59

				</td>
<td>0.055</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_RUBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_RUBKRW', '42', event);" target="_parent">




					러시아 RUB

				</a></td>
<td class="sale">16.09</td>
<td>


						17.61

				</td>
<td>


						13.28

				</td>
<td>


						16.65

				</td>
<td>


						15.53

				</td>
<td>0.012</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HUFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HUFKRW', '43', event);" target="_parent">




					헝가리 HUF

				</a></td>
<td class="sale">3.89</td>
<td>


						4.25

				</td>
<td>


						3.58

				</td>
<td>


						3.93

				</td>
<td>


						3.85

				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PLNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PLNKRW', '44', event);" target="_parent">




					폴란드 PLN

				</a></td>
<td class="sale">311.54</td>
<td>


						336.46

				</td>
<td>


						286.62

				</td>
<td>


						314.96

				</td>
<td>


						308.12

				</td>
<td>0.237</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_LKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_LKRKRW', '45', event);" target="_parent">




					스리랑카 LKR

				</a></td>
<td class="sale">4.11</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DZDKRW', '46', event);" target="_parent">




					알제리 DZD

				</a></td>
<td class="sale">9.71</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KESKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KESKRW', '47', event);" target="_parent">




					케냐 KES

				</a></td>
<td class="sale">9.75</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_COPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_COPKRW', '48', event);" target="_parent">




					콜롬비아 COP

				</a></td>
<td class="sale">0.29</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>

In [19]:
# find는 html안에서 해당 태그의 첫번째 정보를 출력
tbody = soup.find('tbody')

In [20]:
# find_all() 해당 태그의 전체 정보를 리스트의 형태로 출력
soup.find_all('td')[0].get_text().replace('\n','').strip('\t')
# soup.find_all('td')[0].get_text().replace('\n','').replace('\t','')

'미국 USD'

In [21]:
# find_all() 해당 태그의 전체 정보를 리스트의 형태로 출력
data_list = soup.find_all('td')

In [22]:
# data_list를 이용하여 2차원 배열로 새로운 리스트를 생성
# 1차원 리스트 생성
# [[7개씩]], [[7개씩]], [[7개씩]], [[7개씩]] -> 2차원 리스트

In [23]:
# 1차원 리스트 생성
_list =[]
for i in data_list:
    x = i.get_text()
    x = x.replace('\n','')
    x = x.strip('\t')
    _list.append(x)
_list

['미국 USD',
 '1,316.30',
 '1,339.33',
 '1,293.27',
 '1,329.10',
 '1,303.50',
 '1.000',
 '유럽연합 EUR',
 '1,445.17',
 '1,473.92',
 '1,416.42',
 '1,459.62',
 '1,430.72',
 '1.098',
 '일본 JPY (100엔)',
 '981.69',
 '998.86',
 '964.52',
 '991.31',
 '972.07',
 '0.746',
 '중국 CNY',
 '191.41',
 '200.98',
 '181.84',
 '193.32',
 '189.50',
 '0.145',
 '홍콩 HKD',
 '167.72',
 '171.02',
 '164.42',
 '169.39',
 '166.05',
 '0.127',
 '대만 TWD',
 '43.16',
 '48.81',
 '38.85',
 'N/A',
 'N/A',
 '0.033',
 '영국 GBP',
 '1,635.77',
 '1,667.99',
 '1,603.55',
 '1,652.12',
 '1,619.42',
 '1.243',
 '오만 OMR',
 '3,418.78',
 '3,723.05',
 '3,213.66',
 'N/A',
 'N/A',
 '2.597',
 '캐나다 CAD',
 '982.94',
 '1,002.30',
 '963.58',
 '992.76',
 '973.12',
 '0.747',
 '스위스 CHF',
 '1,468.76',
 '1,497.69',
 '1,439.83',
 '1,483.44',
 '1,454.08',
 '1.116',
 '스웨덴 SEK',
 '127.68',
 '130.80',
 '124.56',
 '128.95',
 '126.41',
 '0.097',
 '호주 AUD',
 '886.33',
 '903.79',
 '868.87',
 '895.19',
 '877.47',
 '0.673',
 '뉴질랜드 NZD',
 '817.42',
 '833.52',
 '801.32',
 '825.59',
 '809.25',
 '0.621',
 '체코 CZK',
 '61.64',
 '66.87',
 '56.10',
 '62.31',
 '60.97',
 '0.047',
 '칠레 CLP',
 '1.66',
 '1.82',
 '1.50',
 'N/A',
 'N/A',
 '0.001',
 '튀르키예 TRY',
 '67.86',
 'N/A',
 'N/A',
 '68.60',
 '67.12',
 '0.052',
 '몽골 MNT',
 '0.38',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '이스라엘 ILS',
 '360.86',
 '396.94',
 '332.00',
 'N/A',
 'N/A',
 '0.274',
 '덴마크 DKK',
 '193.94',
 '198.69',
 '189.19',
 '195.87',
 '192.01',
 '0.147',
 '노르웨이 NOK',
 '125.66',
 '128.73',
 '122.59',
 '126.91',
 '124.41',
 '0.096',
 '사우디아라비아 SAR',
 '350.94',
 '373.04',
 '326.73',
 '354.44',
 '347.44',
 '0.267',
 '쿠웨이트 KWD',
 '4,295.46',
 '4,574.66',
 '3,951.83',
 '4,338.41',
 '4,252.51',
 '3.263',
 '바레인 BHD',
 '3,491.23',
 '3,714.66',
 '3,211.94',
 '3,526.14',
 '3,456.32',
 '2.652',
 '아랍에미리트 AED',
 '358.43',
 '378.14',
 '333.70',
 '362.01',
 '354.85',
 '0.272',
 '요르단 JOD',
 '1,855.51',
 '2,020.65',
 '1,707.07',
 'N/A',
 'N/A',
 '1.410',
 '이집트 EGP',
 '42.60',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.032',
 '태국 THB',
 '38.43',
 '40.35',
 '36.13',
 '38.81',
 '38.05',
 '0.029',
 '싱가포르 SGD',
 '987.95',
 '1,007.61',
 '968.29',
 '997.82',
 '978.08',
 '0.751',
 '말레이시아 MYR',
 '296.97',
 '315.67',
 '275.00',
 'N/A',
 '294.01',
 '0.226',
 '인도네시아 IDR 100',
 '8.89',
 '9.77',
 '8.01',
 '8.97',
 '8.81',
 '0.007',
 '카타르 QAR',
 '360.81',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.274',
 '카자흐스탄 KZT',
 '2.91',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.002',
 '브루나이 BND',
 '987.95',
 '1,027.46',
 '928.68',
 'N/A',
 'N/A',
 '0.751',
 '인도 INR',
 '16.03',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.012',
 '파키스탄 PKR',
 '4.64',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.004',
 '방글라데시 BDT',
 '12.40',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.009',
 '필리핀 PHP',
 '23.53',
 '25.88',
 '21.61',
 '23.76',
 '23.30',
 '0.018',
 '멕시코 MXN',
 '72.93',
 '80.22',
 '66.81',
 '73.65',
 '72.21',
 '0.055',
 '브라질 BRL',
 '264.00',
 '290.92',
 '237.60',
 'N/A',
 '260.84',
 '0.201',
 '베트남 VND 100',
 '5.60',
 '6.26',
 '4.94',
 '5.65',
 '5.55',
 '0.004',
 '남아프리카 공화국 ZAR',
 '72.45',
 '78.24',
 '66.66',
 '73.31',
 '71.59',
 '0.055',
 '러시아 RUB',
 '16.09',
 '17.61',
 '13.28',
 '16.65',
 '15.53',
 '0.012',
 '헝가리 HUF',
 '3.89',
 '4.25',
 '3.58',
 '3.93',
 '3.85',
 '0.003',
 '폴란드 PLN',
 '311.54',
 '336.46',
 '286.62',
 '314.96',
 '308.12',
 '0.237',
 '스리랑카 LKR',
 '4.11',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.003',
 '알제리 DZD',
 '9.71',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.007',
 '케냐 KES',
 '9.75',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.007',
 '콜롬비아 COP',
 '0.29',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '탄자니아 TZS',
 '0.56',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '네팔 NPR',
 '10.03',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.008',
 '루마니아 RON',
 '292.76',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.222',
 '리비아 LYD',
 '276.11',
 'N/A',
 'N/A',
 '278.87',
 '273.35',
 '0.210',
 '마카오 MOP',
 '162.71',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.124',
 '미얀마 MMK',
 '0.63',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.001',
 '에티오피아 ETB',
 '24.16',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.018',
 '우즈베키스탄 UZS',
 '0.12',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '캄보디아 KHR',
 '0.32',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '피지 FJD',
 '589.97',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.448']

In [29]:
len(_list)//7

58

In [30]:
list(range(0, (len(_list)//7), 1))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57]

In [35]:
for i in range(0, (len(_list)//7), 1):
    x = []
    for j in range(i*7, (i+1)*7, 1):
        x.append(j)
    print(x)

[0, 1, 2, 3, 4, 5, 6]
[7, 8, 9, 10, 11, 12, 13]
[14, 15, 16, 17, 18, 19, 20]
[21, 22, 23, 24, 25, 26, 27]
[28, 29, 30, 31, 32, 33, 34]
[35, 36, 37, 38, 39, 40, 41]
[42, 43, 44, 45, 46, 47, 48]
[49, 50, 51, 52, 53, 54, 55]
[56, 57, 58, 59, 60, 61, 62]
[63, 64, 65, 66, 67, 68, 69]
[70, 71, 72, 73, 74, 75, 76]
[77, 78, 79, 80, 81, 82, 83]
[84, 85, 86, 87, 88, 89, 90]
[91, 92, 93, 94, 95, 96, 97]
[98, 99, 100, 101, 102, 103, 104]
[105, 106, 107, 108, 109, 110, 111]
[112, 113, 114, 115, 116, 117, 118]
[119, 120, 121, 122, 123, 124, 125]
[126, 127, 128, 129, 130, 131, 132]
[133, 134, 135, 136, 137, 138, 139]
[140, 141, 142, 143, 144, 145, 146]
[147, 148, 149, 150, 151, 152, 153]
[154, 155, 156, 157, 158, 159, 160]
[161, 162, 163, 164, 165, 166, 167]
[168, 169, 170, 171, 172, 173, 174]
[175, 176, 177, 178, 179, 180, 181]
[182, 183, 184, 185, 186, 187, 188]
[189, 190, 191, 192, 193, 194, 195]
[196, 197, 198, 199, 200, 201, 202]
[203, 204, 205, 206, 207, 208, 209]
[210, 211, 212, 213, 214, 215, 216]
[217, 218, 219, 220, 221, 222, 223]
[224, 225, 226, 227, 228, 229, 230]
[231, 232, 233, 234, 235, 236, 237]
[238, 239, 240, 241, 242, 243, 244]
[245, 246, 247, 248, 249, 250, 251]
[252, 253, 254, 255, 256, 257, 258]
[259, 260, 261, 262, 263, 264, 265]
[266, 267, 268, 269, 270, 271, 272]
[273, 274, 275, 276, 277, 278, 279]
[280, 281, 282, 283, 284, 285, 286]
[287, 288, 289, 290, 291, 292, 293]
[294, 295, 296, 297, 298, 299, 300]
[301, 302, 303, 304, 305, 306, 307]
[308, 309, 310, 311, 312, 313, 314]
[315, 316, 317, 318, 319, 320, 321]
[322, 323, 324, 325, 326, 327, 328]
[329, 330, 331, 332, 333, 334, 335]
[336, 337, 338, 339, 340, 341, 342]
[343, 344, 345, 346, 347, 348, 349]
[350, 351, 352, 353, 354, 355, 356]
[357, 358, 359, 360, 361, 362, 363]
[364, 365, 366, 367, 368, 369, 370]
[371, 372, 373, 374, 375, 376, 377]
[378, 379, 380, 381, 382, 383, 384]
[385, 386, 387, 388, 389, 390, 391]
[392, 393, 394, 395, 396, 397, 398]
[399, 400, 401, 402, 403, 404, 405]

In [37]:
# 2차원으로 나옴
result = []
for i in range(0, (len(_list)//7), 1):
    x = []
    for j in range(i*7, (i+1)*7, 1):
        x.append(_list[j])
    result.append(x)
result

[['미국 USD',
  '1,316.30',
  '1,339.33',
  '1,293.27',
  '1,329.10',
  '1,303.50',
  '1.000'],
 ['유럽연합 EUR',
  '1,445.17',
  '1,473.92',
  '1,416.42',
  '1,459.62',
  '1,430.72',
  '1.098'],
 ['일본 JPY (100엔)', '981.69', '998.86', '964.52', '991.31', '972.07', '0.746'],
 ['중국 CNY', '191.41', '200.98', '181.84', '193.32', '189.50', '0.145'],
 ['홍콩 HKD', '167.72', '171.02', '164.42', '169.39', '166.05', '0.127'],
 ['대만 TWD', '43.16', '48.81', '38.85', 'N/A', 'N/A', '0.033'],
 ['영국 GBP',
  '1,635.77',
  '1,667.99',
  '1,603.55',
  '1,652.12',
  '1,619.42',
  '1.243'],
 ['오만 OMR', '3,418.78', '3,723.05', '3,213.66', 'N/A', 'N/A', '2.597'],
 ['캐나다 CAD', '982.94', '1,002.30', '963.58', '992.76', '973.12', '0.747'],
 ['스위스 CHF',
  '1,468.76',
  '1,497.69',
  '1,439.83',
  '1,483.44',
  '1,454.08',
  '1.116'],
 ['스웨덴 SEK', '127.68', '130.80', '124.56', '128.95', '126.41', '0.097'],
 ['호주 AUD', '886.33', '903.79', '868.87', '895.19', '877.47', '0.673'],
 ['뉴질랜드 NZD', '817.42', '833.52', '801.32', '825.59', '809.25', '0.621'],
 ['체코 CZK', '61.64', '66.87', '56.10', '62.31', '60.97', '0.047'],
 ['칠레 CLP', '1.66', '1.82', '1.50', 'N/A', 'N/A', '0.001'],
 ['튀르키예 TRY', '67.86', 'N/A', 'N/A', '68.60', '67.12', '0.052'],
 ['몽골 MNT', '0.38', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['이스라엘 ILS', '360.86', '396.94', '332.00', 'N/A', 'N/A', '0.274'],
 ['덴마크 DKK', '193.94', '198.69', '189.19', '195.87', '192.01', '0.147'],
 ['노르웨이 NOK', '125.66', '128.73', '122.59', '126.91', '124.41', '0.096'],
 ['사우디아라비아 SAR', '350.94', '373.04', '326.73', '354.44', '347.44', '0.267'],
 ['쿠웨이트 KWD',
  '4,295.46',
  '4,574.66',
  '3,951.83',
  '4,338.41',
  '4,252.51',
  '3.263'],
 ['바레인 BHD',
  '3,491.23',
  '3,714.66',
  '3,211.94',
  '3,526.14',
  '3,456.32',
  '2.652'],
 ['아랍에미리트 AED', '358.43', '378.14', '333.70', '362.01', '354.85', '0.272'],
 ['요르단 JOD', '1,855.51', '2,020.65', '1,707.07', 'N/A', 'N/A', '1.410'],
 ['이집트 EGP', '42.60', 'N/A', 'N/A', 'N/A', 'N/A', '0.032'],
 ['태국 THB', '38.43', '40.35', '36.13', '38.81', '38.05', '0.029'],
 ['싱가포르 SGD', '987.95', '1,007.61', '968.29', '997.82', '978.08', '0.751'],
 ['말레이시아 MYR', '296.97', '315.67', '275.00', 'N/A', '294.01', '0.226'],
 ['인도네시아 IDR 100', '8.89', '9.77', '8.01', '8.97', '8.81', '0.007'],
 ['카타르 QAR', '360.81', 'N/A', 'N/A', 'N/A', 'N/A', '0.274'],
 ['카자흐스탄 KZT', '2.91', 'N/A', 'N/A', 'N/A', 'N/A', '0.002'],
 ['브루나이 BND', '987.95', '1,027.46', '928.68', 'N/A', 'N/A', '0.751'],
 ['인도 INR', '16.03', 'N/A', 'N/A', 'N/A', 'N/A', '0.012'],
 ['파키스탄 PKR', '4.64', 'N/A', 'N/A', 'N/A', 'N/A', '0.004'],
 ['방글라데시 BDT', '12.40', 'N/A', 'N/A', 'N/A', 'N/A', '0.009'],
 ['필리핀 PHP', '23.53', '25.88', '21.61', '23.76', '23.30', '0.018'],
 ['멕시코 MXN', '72.93', '80.22', '66.81', '73.65', '72.21', '0.055'],
 ['브라질 BRL', '264.00', '290.92', '237.60', 'N/A', '260.84', '0.201'],
 ['베트남 VND 100', '5.60', '6.26', '4.94', '5.65', '5.55', '0.004'],
 ['남아프리카 공화국 ZAR', '72.45', '78.24', '66.66', '73.31', '71.59', '0.055'],
 ['러시아 RUB', '16.09', '17.61', '13.28', '16.65', '15.53', '0.012'],
 ['헝가리 HUF', '3.89', '4.25', '3.58', '3.93', '3.85', '0.003'],
 ['폴란드 PLN', '311.54', '336.46', '286.62', '314.96', '308.12', '0.237'],
 ['스리랑카 LKR', '4.11', 'N/A', 'N/A', 'N/A', 'N/A', '0.003'],
 ['알제리 DZD', '9.71', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['케냐 KES', '9.75', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['콜롬비아 COP', '0.29', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['탄자니아 TZS', '0.56', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['네팔 NPR', '10.03', 'N/A', 'N/A', 'N/A', 'N/A', '0.008'],
 ['루마니아 RON', '292.76', 'N/A', 'N/A', 'N/A', 'N/A', '0.222'],
 ['리비아 LYD', '276.11', 'N/A', 'N/A', '278.87', '273.35', '0.210'],
 ['마카오 MOP', '162.71', 'N/A', 'N/A', 'N/A', 'N/A', '0.124'],
 ['미얀마 MMK', '0.63', 'N/A', 'N/A', 'N/A', 'N/A', '0.001'],
 ['에티오피아 ETB', '24.16', 'N/A', 'N/A', 'N/A', 'N/A', '0.018'],
 ['우즈베키스탄 UZS', '0.12', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['캄보디아 KHR', '0.32', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['피지 FJD', '589.97', 'N/A', 'N/A', 'N/A', 'N/A', '0.448']]

In [41]:
# 7개씩 나눠져있음
_list[7:14]

['유럽연합 EUR',
 '1,445.17',
 '1,473.92',
 '1,416.42',
 '1,459.62',
 '1,430.72',
 '1.098']

In [43]:
# 7개씩 나눠져있음
_list[14:21]

['일본 JPY (100엔)', '981.69', '998.86', '964.52', '991.31', '972.07', '0.746']

In [46]:
result = []
for i in range(len(_list)//7):
    result.append(_list[i*7:(i+1)*7])
result

[['미국 USD',
  '1,316.30',
  '1,339.33',
  '1,293.27',
  '1,329.10',
  '1,303.50',
  '1.000'],
 ['유럽연합 EUR',
  '1,445.17',
  '1,473.92',
  '1,416.42',
  '1,459.62',
  '1,430.72',
  '1.098'],
 ['일본 JPY (100엔)', '981.69', '998.86', '964.52', '991.31', '972.07', '0.746'],
 ['중국 CNY', '191.41', '200.98', '181.84', '193.32', '189.50', '0.145'],
 ['홍콩 HKD', '167.72', '171.02', '164.42', '169.39', '166.05', '0.127'],
 ['대만 TWD', '43.16', '48.81', '38.85', 'N/A', 'N/A', '0.033'],
 ['영국 GBP',
  '1,635.77',
  '1,667.99',
  '1,603.55',
  '1,652.12',
  '1,619.42',
  '1.243'],
 ['오만 OMR', '3,418.78', '3,723.05', '3,213.66', 'N/A', 'N/A', '2.597'],
 ['캐나다 CAD', '982.94', '1,002.30', '963.58', '992.76', '973.12', '0.747'],
 ['스위스 CHF',
  '1,468.76',
  '1,497.69',
  '1,439.83',
  '1,483.44',
  '1,454.08',
  '1.116'],
 ['스웨덴 SEK', '127.68', '130.80', '124.56', '128.95', '126.41', '0.097'],
 ['호주 AUD', '886.33', '903.79', '868.87', '895.19', '877.47', '0.673'],
 ['뉴질랜드 NZD', '817.42', '833.52', '801.32', '825.59', '809.25', '0.621'],
 ['체코 CZK', '61.64', '66.87', '56.10', '62.31', '60.97', '0.047'],
 ['칠레 CLP', '1.66', '1.82', '1.50', 'N/A', 'N/A', '0.001'],
 ['튀르키예 TRY', '67.86', 'N/A', 'N/A', '68.60', '67.12', '0.052'],
 ['몽골 MNT', '0.38', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['이스라엘 ILS', '360.86', '396.94', '332.00', 'N/A', 'N/A', '0.274'],
 ['덴마크 DKK', '193.94', '198.69', '189.19', '195.87', '192.01', '0.147'],
 ['노르웨이 NOK', '125.66', '128.73', '122.59', '126.91', '124.41', '0.096'],
 ['사우디아라비아 SAR', '350.94', '373.04', '326.73', '354.44', '347.44', '0.267'],
 ['쿠웨이트 KWD',
  '4,295.46',
  '4,574.66',
  '3,951.83',
  '4,338.41',
  '4,252.51',
  '3.263'],
 ['바레인 BHD',
  '3,491.23',
  '3,714.66',
  '3,211.94',
  '3,526.14',
  '3,456.32',
  '2.652'],
 ['아랍에미리트 AED', '358.43', '378.14', '333.70', '362.01', '354.85', '0.272'],
 ['요르단 JOD', '1,855.51', '2,020.65', '1,707.07', 'N/A', 'N/A', '1.410'],
 ['이집트 EGP', '42.60', 'N/A', 'N/A', 'N/A', 'N/A', '0.032'],
 ['태국 THB', '38.43', '40.35', '36.13', '38.81', '38.05', '0.029'],
 ['싱가포르 SGD', '987.95', '1,007.61', '968.29', '997.82', '978.08', '0.751'],
 ['말레이시아 MYR', '296.97', '315.67', '275.00', 'N/A', '294.01', '0.226'],
 ['인도네시아 IDR 100', '8.89', '9.77', '8.01', '8.97', '8.81', '0.007'],
 ['카타르 QAR', '360.81', 'N/A', 'N/A', 'N/A', 'N/A', '0.274'],
 ['카자흐스탄 KZT', '2.91', 'N/A', 'N/A', 'N/A', 'N/A', '0.002'],
 ['브루나이 BND', '987.95', '1,027.46', '928.68', 'N/A', 'N/A', '0.751'],
 ['인도 INR', '16.03', 'N/A', 'N/A', 'N/A', 'N/A', '0.012'],
 ['파키스탄 PKR', '4.64', 'N/A', 'N/A', 'N/A', 'N/A', '0.004'],
 ['방글라데시 BDT', '12.40', 'N/A', 'N/A', 'N/A', 'N/A', '0.009'],
 ['필리핀 PHP', '23.53', '25.88', '21.61', '23.76', '23.30', '0.018'],
 ['멕시코 MXN', '72.93', '80.22', '66.81', '73.65', '72.21', '0.055'],
 ['브라질 BRL', '264.00', '290.92', '237.60', 'N/A', '260.84', '0.201'],
 ['베트남 VND 100', '5.60', '6.26', '4.94', '5.65', '5.55', '0.004'],
 ['남아프리카 공화국 ZAR', '72.45', '78.24', '66.66', '73.31', '71.59', '0.055'],
 ['러시아 RUB', '16.09', '17.61', '13.28', '16.65', '15.53', '0.012'],
 ['헝가리 HUF', '3.89', '4.25', '3.58', '3.93', '3.85', '0.003'],
 ['폴란드 PLN', '311.54', '336.46', '286.62', '314.96', '308.12', '0.237'],
 ['스리랑카 LKR', '4.11', 'N/A', 'N/A', 'N/A', 'N/A', '0.003'],
 ['알제리 DZD', '9.71', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['케냐 KES', '9.75', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['콜롬비아 COP', '0.29', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['탄자니아 TZS', '0.56', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['네팔 NPR', '10.03', 'N/A', 'N/A', 'N/A', 'N/A', '0.008'],
 ['루마니아 RON', '292.76', 'N/A', 'N/A', 'N/A', 'N/A', '0.222'],
 ['리비아 LYD', '276.11', 'N/A', 'N/A', '278.87', '273.35', '0.210'],
 ['마카오 MOP', '162.71', 'N/A', 'N/A', 'N/A', 'N/A', '0.124'],
 ['미얀마 MMK', '0.63', 'N/A', 'N/A', 'N/A', 'N/A', '0.001'],
 ['에티오피아 ETB', '24.16', 'N/A', 'N/A', 'N/A', 'N/A', '0.018'],
 ['우즈베키스탄 UZS', '0.12', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['캄보디아 KHR', '0.32', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['피지 FJD', '589.97', 'N/A', 'N/A', 'N/A', 'N/A', '0.448']]

In [47]:
import pandas as pd

In [48]:
columns = ['통화명', '매매기준율','현찰(구매)', '현찰(판매)', '송금(보낼때)', '송금(받을때)','미화환산율']

In [50]:
pd.DataFrame(result, columns=columns).to_csv('test.csv', index=False)

In [52]:
import mod_sql

In [53]:
db = mod_sql.Database('localhost', 'root', '1n0s2h5*', 'ubion',3306)

In [54]:
# DB에 table 생성 (naver)
# 필드는 7개 모두 필드의 타입은 문자열로 구성
# 통화명 필드는 primary key로 지정

sql ="""
    create
    table
    `naver`(
        `통화명` varchar(16),
        `매매기준율` varchar(16),
        `현찰(구매)` varchar(16),
        `현찰(판매)` varchar(16),
        `송금(보낼때)` varchar(16),
        `송금(받을때)` varchar(16),
        `미화환산율` varchar(16)
    )
"""
db.sql_query(sql)

'Query OK'

In [55]:
# naver라는 이름으로 생성한 테이블에 데이터 삽입
# 데이터를 삽입하는 insert문을 작상
sql = """
    insert
    into
    naver
    values(
        '통화명',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6'
    )
"""

db.sql_query(sql)

'Query OK'

In [58]:
sql = """
    insert
    into
    naver
    values
    (%s,%s,%s,%s,%s,%s,%s)
"""

values = [1,2,3,4,5,6,7]

db.sql_query(sql, values)

'Query OK'

In [61]:
# 데이터 지우기, drop은 테이블 지우기
sql = """
    delete
    from
    naver
    where
    통화명 = '통화명'
"""
db.sql_query(sql)

'Query OK'

In [62]:
sql = """
    delete
    from
    naver
    where
    통화명 = '1'
"""
db.sql_query(sql)

'Query OK'

In [64]:
result[0]

['미국 USD', '1,316.30', '1,339.33', '1,293.27', '1,329.10', '1,303.50', '1.000']

In [74]:
# result 변수의 데이터를 naver 테이블에 삽입
sql = """
    insert
    into
    naver
    values(%s,%s,%s,%s,%s,%s,%s)
"""
for i in range(len(result)):
    values = result[i]
    db.sql_query(sql, values)

In [70]:
sql = """
    select * from naver
"""
db.sql_query(sql)

              통화명     매매기준율    현찰(구매)    현찰(판매)   송금(보낼때)   송금(받을때)  미화환산율
0          미국 USD  1,316.30  1,339.33  1,293.27  1,329.10  1,303.50  1.000
1        유럽연합 EUR  1,445.17  1,473.92  1,416.42  1,459.62  1,430.72  1.098
2   일본 JPY (100엔)    981.69    998.86    964.52    991.31    972.07  0.746
3          중국 CNY    191.41    200.98    181.84    193.32    189.50  0.145
4          홍콩 HKD    167.72    171.02    164.42    169.39    166.05  0.127
5          대만 TWD     43.16     48.81     38.85       N/A       N/A  0.033
6          영국 GBP  1,635.77  1,667.99  1,603.55  1,652.12  1,619.42  1.243
7          오만 OMR  3,418.78  3,723.05  3,213.66       N/A       N/A  2.597
8         캐나다 CAD    982.94  1,002.30    963.58    992.76    973.12  0.747
9         스위스 CHF  1,468.76  1,497.69  1,439.83  1,483.44  1,454.08  1.116
10        스웨덴 SEK    127.68    130.80    124.56    128.95    126.41  0.097
11         호주 AUD    886.33    903.79    868.87    895.19    877.47  0.673
12       뉴질랜드 NZD    817.42    833.52    801.32    825.59    809.25  0.621
13         체코 CZK     61.64     66.87     56.10     62.31     60.97  0.047
14         칠레 CLP      1.66      1.82      1.50       N/A       N/A  0.001
15       튀르키예 TRY     67.86       N/A       N/A     68.60     67.12  0.052
16         몽골 MNT      0.38       N/A       N/A       N/A       N/A  0.000
17       이스라엘 ILS    360.86    396.94    332.00       N/A       N/A  0.274
18        덴마크 DKK    193.94    198.69    189.19    195.87    192.01  0.147
19       노르웨이 NOK    125.66    128.73    122.59    126.91    124.41  0.096
20    사우디아라비아 SAR    350.94    373.04    326.73    354.44    347.44  0.267
21       쿠웨이트 KWD  4,295.46  4,574.66  3,951.83  4,338.41  4,252.51  3.263
22        바레인 BHD  3,491.23  3,714.66  3,211.94  3,526.14  3,456.32  2.652
23     아랍에미리트 AED    358.43    378.14    333.70    362.01    354.85  0.272
24        요르단 JOD  1,855.51  2,020.65  1,707.07       N/A       N/A  1.410
25        이집트 EGP     42.60       N/A       N/A       N/A       N/A  0.032
26         태국 THB     38.43     40.35     36.13     38.81     38.05  0.029
27       싱가포르 SGD    987.95  1,007.61    968.29    997.82    978.08  0.751
28      말레이시아 MYR    296.97    315.67    275.00       N/A    294.01  0.226
29  인도네시아 IDR 100      8.89      9.77      8.01      8.97      8.81  0.007
30        카타르 QAR    360.81       N/A       N/A       N/A       N/A  0.274
31      카자흐스탄 KZT      2.91       N/A       N/A       N/A       N/A  0.002
32       브루나이 BND    987.95  1,027.46    928.68       N/A       N/A  0.751
33         인도 INR     16.03       N/A       N/A       N/A       N/A  0.012
34       파키스탄 PKR      4.64       N/A       N/A       N/A       N/A  0.004
35      방글라데시 BDT     12.40       N/A       N/A       N/A       N/A  0.009
36        필리핀 PHP     23.53     25.88     21.61     23.76     23.30  0.018
37        멕시코 MXN     72.93     80.22     66.81     73.65     72.21  0.055
38        브라질 BRL    264.00    290.92    237.60       N/A    260.84  0.201
39    베트남 VND 100      5.60      6.26      4.94      5.65      5.55  0.004
40  남아프리카 공화국 ZAR     72.45     78.24     66.66     73.31     71.59  0.055
41        러시아 RUB     16.09     17.61     13.28     16.65     15.53  0.012
42        헝가리 HUF      3.89      4.25      3.58      3.93      3.85  0.003
43        폴란드 PLN    311.54    336.46    286.62    314.96    308.12  0.237
44       스리랑카 LKR      4.11       N/A       N/A       N/A       N/A  0.003
45        알제리 DZD      9.71       N/A       N/A       N/A       N/A  0.007
46         케냐 KES      9.75       N/A       N/A       N/A       N/A  0.007
47       콜롬비아 COP      0.29       N/A       N/A       N/A       N/A  0.000
48       탄자니아 TZS      0.56       N/A       N/A       N/A       N/A  0.000
49         네팔 NPR     10.03       N/A       N/A       N/A       N/A  0.008
50       루마니아 RON    292.76       N/A       N/A       N/A       N/A  0.222
51        리비아 LYD    276.11       N/A       N/A    278.87    273.35  0.210
52        마카오 MOP    162.71       N/A       N/A       N/A       N/A  0.124
53        미얀마 MMK      0.63       N/A       N/A       N/A       N/A  0.001
54      에티오피아 ETB     24.16       N/A       N/A       N/A       N/A  0.018
55     우즈베키스탄 UZS      0.12       N/A       N/A       N/A       N/A  0.000
56       캄보디아 KHR      0.32       N/A       N/A       N/A       N/A  0.000
57         피지 FJD    589.97       N/A       N/A       N/A       N/A  0.448

In [82]:
sql = """
    insert
    into
    naver2
    (`통화명`, `매매기준율`, `현찰(구매)`, `현찰(판매)`, `송금(보낼때)`, `송금(받을때)`, `미화환산율`)
    values(%s,%s,%s,%s,%s,%s,%s)
"""
for i in result:
    db.sql_query(sql, i)

In [81]:
sql = """
    delete
    from
    naver2
"""
db.sql_query(sql)

'Query OK'